### ISSUE TITLE
metrics are not always visualized in the metrics page

### ISSUE THREAD

**Issue by fuzzyami** [eleme/banshee#623]
hey guys, i've been loading Banshee with metrics and I always see the first rule visualized (vey nicely!) - but usually none of the rest. I know the metrics are there, but they're not shown when I try to view multiple rules. perhaps you know why?

see this image: only the first metric is shown:

![image](https://cloud.githubusercontent.com/assets/829266/21855560/9721f140-d827-11e6-979d-4f58ff051de1.png)

**Comment by zhaojkun** [comment]
@fuzzyami  Refresh your browser and try again. How about the status of the browser's requests.You can use chrome developer tools to diagnose it.

**Comment by fuzzyami** [comment]
Thanks for those tips. I'm not really a front-end programmer, but here's
what I see:

1. I can see periodic requests for metric-data for the metric that IS
visualized:
like this:
http://localhost:2016/api/metric/data?name=gauge.avg-sys-load1.do-sgp1&start=1484190740&stop=1484203540

2. But i'm NOT seeing any requests for other metrics.

So I think the problem is with the web-panel - its not asking for the data.

also, there are a bunch of js errors. here are two examples:

vendor.min-0c80728f.js:134Error: transition prevented
    at v [as $get] (
http://localhost:2016/js/vendor.min-0c80728f.js:1206:16169)
    at Object.invoke (http://localhost:2016/js/vendor.min-0c80728f.js:55:175
)
    at http://localhost:2016/js/vendor.min-0c80728f.js:56:486
    at d (http://localhost:2016/js/vendor.min-0c80728f.js:54:92)
    at e (http://localhost:2016/js/vendor.min-0c80728f.js:54:333)
    at Object.invoke (http://localhost:2016/js/vendor.min-0c80728f.js:54:418
)
    at http://localhost:2016/js/vendor.min-0c80728f.js:66:276
    at q (http://localhost:2016/js/vendor.min-0c80728f.js:19:351)
    at Object.<anonymous> (
http://localhost:2016/js/vendor.min-0c80728f.js:66:243)
    at Object.invoke (http://localhost:2016/js/vendor.min-0c80728f.js:55:175)
Possibly unhandled rejection: {}



vendor.min-0c80728f.js:134 TypeError: Cannot read property 'length' of
undefined
    at http://localhost:2016/js/banshee.min-51dcf8df.js:4:9893
    at Array.forEach (native)
    at p (http://localhost:2016/js/banshee.min-51dcf8df.js:4:9695)
    at http://localhost:2016/js/banshee.min-51dcf8df.js:4:11213
    at e.r (http://localhost:2016/js/vendor.min-0c80728f.js:1249:7359)
    at e.a.on (http://localhost:2016/js/vendor.min-0c80728f.js:1249:2862)
    at l.e.on (http://localhost:2016/js/vendor.min-0c80728f.js:1249:7967)
    at HTMLDivElement.<anonymous> (
http://localhost:2016/js/vendor.min-0c80728f.js:1249:9966)
    at http://localhost:2016/js/vendor.min-0c80728f.js:1246:15103
    at Y (http://localhost:2016/js/vendor.min-0c80728f.js:1244:4505)
Possibly unhandled rejection: {}

**Comment by zhaojkun** [comment]
@fuzzyami This problem has been solved in https://github.com/eleme/banshee/pull/626

**Comment by fuzzyami** [comment]
I can confirm this is now working. thanks!
