### ISSUE TITLE
运行时报错：panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mayuncun** [eleme/banshee#645]
DEBUG 2017-07-07 16:58:45 config/config.go:210 read config from config/exampleConfig.yaml..
DEBUG 2017-07-07 16:58:45 storage/db.go:49 create dir ./data
DEBUG 2017-07-07 16:58:45 indexdb/db.go:79 init index from indexdb..
DEBUG 2017-07-07 16:58:45 metricdb/db.go:112 dir data/metric created
DEBUG 2017-07-07 16:58:45 eventdb/db.go:115 dir data/event created
DEBUG 2017-07-07 16:58:45 storage/db.go:90 storage is opened successfully
DEBUG 2017-07-07 16:58:45 filter/filter.go:125 init filter's rules from cache..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x49016e]

goroutine 1 [running]:
panic(0x8e5b80, 0xc4200100c0)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/eleme/banshee/filter.(*Filter).initFromDB(0xc420012bd0, 0xc42018d160)
        /usr/banshee/src/github.com/eleme/banshee/filter/filter.go:127 +0x6e
github.com/eleme/banshee/filter.(*Filter).Init(0xc420012bd0, 0xc42018d160)
        /usr/banshee/src/github.com/eleme/banshee/filter/filter.go:138 +0x35
main.initFilter()
        /usr/banshee/main.go:94 +0x23a
main.init.1()
        /usr/banshee/main.go:123 +0x72
main.init()
        /usr/banshee/main.go:141 +0x197

**Comment by zhaojkun** [comment]
@mayuncun 使用的是最新版本，还是哪个版本；配置文件是怎样的

**Comment by mayuncun** [comment]
版本是0.25，配置文件用的是config/exampleConfig.xml

运行命令  ./banshee -c config/exampleConfig.yaml -d 以后，在data目录下是不是应该有四个子目录？目前只有三个：index、event和metric，没有admin。

// initFromDB inits rules from db.
func (f *Filter) initFromDB(db *storage.DB) {
	log.Debugf("init filter's rules from cache..")
	// Listen rules changes.
这句话报错：**db.Admin.RulesCache.OnAdd(f.addRuleCh)**，怀疑是db.Admin为空。
	db.Admin.RulesCache.OnDel(f.delRuleCh)
	// Add rules from cache
	rules := db.Admin.RulesCache.All()
	for _, rule := range rules {
		f.addRule(rule)
	}
}

**Comment by zhaojkun** [comment]
现在 `admin` 数据是依赖 `mysql` 的。如果没有配置的话，应该直接退出的。如果需要使用sqlite进行测试的话，可以checkout 到上一个pr `b50fecab8002b6e05932596bfe6dde9`。具体到你这个问题，可以打印下`db.Admin`看下是否为`nil`

**Comment by mayuncun** [comment]
@ zhaojkun 使用mysql和如下配置依然报上面的错误：

storage:
    path: ./data
    admin:
          host: localhost
          user: root
          password: root
          port: 3306
          dbname: mysql

注：连接信息没有问题。

**Comment by zhaojkun** [comment]
@mayuncun 我这边仍然复现不了
